networks:
  traefik:
    external: true

# description: bytebin is a fast & lightweight content storage web service.
# https://github.com/lucko/bytebin
# https://github.com/lucko/bytesocks

services:
  bytebin:
    image: ghcr.io/lucko/bytebin:${BYTEBIN_DOCKER_TAG:-latest}
    env_file:
      - ./services-enabled/bytebin.env
    container_name: ${BYTEBIN_CONTAINER_NAME:-bytebin}
    restart: ${BYTEBIN_RESTART:-unless-stopped}
    mem_limit: ${BYTEBIN_MEM_LIMIT:-200g}
    user: "${PUID:-1000}:${PGID:-1000}"
    networks:
      - traefik
    volumes:
      - ./etc/bytebin/data:/opt/bytebin/content
      - ./etc/bytebin/db:/opt/bytebin/db
      - ./etc/bytebin/bytebin-logs:/opt/bytebin/logs
      - ./etc/bytebin/bytebin-tmp:/opt/bytebin/tmp
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${BYTEBIN_HOST_NAME:-bytebin}.${HOST_DOMAIN}
      - traefik.enable=${BYTEBIN_TRAEFIK_ENABLED:-true}
      - traefik.http.routers.bytebin-data-disabled.entrypoints=websecure
      - traefik.http.routers.bytebin-data-disabled.priority=200
      - traefik.http.routers.bytebin-data-disabled.rule=Host(`${BYTEBIN_HOST_NAME:-bytebin}.${HOST_DOMAIN}`) && Path(`/data/`)
      - traefik.http.routers.bytebin-data-disabled.service=noop@internal
      - traefik.http.routers.bytebin-data.entrypoints=websecure
      - traefik.http.routers.bytebin-data.priority=100
      - traefik.http.routers.bytebin-data.rule=Host(`${BYTEBIN_HOST_NAME:-bytebin}.${HOST_DOMAIN}`) && PathPrefix(`/data/`)
      - traefik.http.routers.bytebin-data.middlewares=bytebin-data-stripprefix
      - traefik.http.routers.bytebin-data.service=bytebin
      - traefik.http.middlewares.bytebin-data-stripprefix.stripprefix.prefixes=/data
      - traefik.http.services.bytebin.loadbalancer.passhostheader=true
      - traefik.http.services.bytebin.loadbalancer.server.scheme=http
      - traefik.http.services.bytebin.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=${BYTEBIN_WATCHTOWER_ENABLED:-true}
      - autoheal=${BYTEBIN_AUTOHEAL_ENABLED:-true}
  bytesocks:
    image: ghcr.io/lucko/bytesocks:${BYTEBIN_DOCKER_TAG:-latest}
    env_file:
      - ./services-enabled/bytebin.env
    container_name: ${BYTESOCKS_CONTAINER_NAME:-bytesocks}
    restart: ${BYTESOCKS_RESTART:-unless-stopped}
    mem_limit: ${BYTESOCKS_MEM_LIMIT:-200g}
    user: "${PUID:-1000}:${PGID:-1000}"
    networks:
      - traefik
    volumes:
      - ./etc/bytebin/bytesocks-logs:/opt/bytesocks/logs
      - ./etc/bytebin/bytesocks-tmp:/opt/bytesocks/tmp
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${BYTEBIN_HOST_NAME:-bytebin}.${HOST_DOMAIN}
      - traefik.enable=${BYTESOCKS_TRAEFIK_ENABLED:-true}
      - traefik.http.routers.bytesocks.entrypoints=websecure
      - traefik.http.routers.bytesocks.rule=Host(`${BYTEBIN_HOST_NAME:-bytebin}.${HOST_DOMAIN}`) && PathPrefix(`/ws/`)
      - traefik.http.routers.bytesocks.middlewares=bytesocks-stripprefix
      - traefik.http.routers.bytesocks.service=bytesocks
      - traefik.http.middlewares.bytesocks-stripprefix.stripprefix.prefixes=/ws
      - traefik.http.services.bytesocks.loadbalancer.passhostheader=true
      - traefik.http.services.bytesocks.loadbalancer.server.scheme=http
      - traefik.http.services.bytesocks.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=${BYTESOCKS_WATCHTOWER_ENABLED:-true}
      - autoheal=${BYTESOCKS_AUTOHEAL_ENABLED:-true}
